"""Add profile_image column to users table

Revision ID: add_profile_image_001
Revises: 518c29929605
Create Date: 2026-01-31 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "add_profile_image_001"
down_revision = "518c29929605"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("profile_image", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profile_image")
    # ### end Alembic commands ###
